config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:new, :create, :show] do
    resources :bookmarks, only: [:new, :create, :index, :destroy]
    resources :movies, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new
    end
  end

  def destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie, :comment)
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :post_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>New bookmark to</h1>

<%= simple_form_for ([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, value_method: :id %>
  <%= f.submit "Add bookmark", class: "btn btn-secondary" %>
<% end %>
  <%# <% raise %>
<%# <%= link_to 'Back', list_bookmark_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to "#", class: "navbar-brand" do %>
        <a href='#'><i class="fa fa-ticket fa-3x"></i></a>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Create new list", class: "btn btn-secondary" %>
<% end %>

app/views/lists/index.html.erb
<h1>Watch Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<hr>
<%= link_to 'Create new list', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>
<hr>
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1>Movies of <%= @list.name %></h1>

<%= link_to 'Add a movie', new_list_bookmark_path(@list) %>
<hr>
<%= link_to 'Back', root_path %>